name: push to azure
on:
  workflow_dispatch:
  # schedule:
    # - cron:  '0 * */1 * *'

jobs:
  load_notion_and_upload_to_azure:
    runs-on: ubuntu-20.04
    env:
      NOTION_AUTH: ${{secrets.NOTION_AUTH}}
      NOTION_DATABASE_ID: ${{secrets.NOTION_DATABASE_ID}}
    permissions: write-all
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v2
        with:
          python-version: '3.8.0'
      - run: pip install notion-client
      - run: python update_content.py
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.85.0'
          extended: true
      - run: git clone --branch dev --depth 1 https://github.com/FarseaSH/hugo-theme-moments.git ./themes/moments
      - name: Hugo build
        run: hugo
      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for GitHub integrations (i.e. PR comments)
          action: "upload"
          ###### Repository/Build Configurations ######
          app_location: "./public" # App source code path relative to repository root