name: update content & push to github page
on:
  - workflow_dispatch
  # schedule:
    # - cron:  '0 * */1 * *'

permissions: write-all

jobs:
  build:
    runs-on: ubuntu-20.04
    env:
      NOTION_AUTH: ${{secrets.NOTION_AUTH}}
      NOTION_DATABASE_ID: ${{secrets.NOTION_DATABASE_ID}}
      HUGO_VERSION: 0.85.0
    steps:
      - name: Checkout repo files
        uses: actions/checkout@v4 
      - uses: actions/setup-python@v2
        with:
          python-version: '3.8.0'
      - run: pip install notion-client
      - run: python update_content.py
      - run: git clone --branch dev --depth 1 https://github.com/FarseaSH/hugo-theme-moments.git ./themes/moments
      - name: Install Hugo CLI
        run: |
          wget -O ${{ runner.temp }}/hugo.deb https://github.com/gohugoio/hugo/releases/download/v0.85.0/hugo_extended_0.85.0_Linux-64bit.deb \
          && sudo dpkg -i ${{ runner.temp }}/hugo.deb          
      - name: Install Dart Sass
        run: sudo snap install dart-sass
      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v4
      - name: Install Node.js dependencies
        run: "[[ -f package-lock.json || -f npm-shrinkwrap.json ]] && npm ci || true"
      - name: Build with Hugo
        env:
          # For maximum backward compatibility with Hugo modules
          HUGO_ENVIRONMENT: production
          HUGO_ENV: production
          TZ: America/Los_Angeles
        run: |
          hugo \
            --gc \
            --minify \
            --baseURL "${{ steps.pages.outputs.base_url }}/"    
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./public
  
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

